source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JWAnimatedImage_Example', :exclusive => true do
  pod 'JWAnimatedImage', :path => '../'
end

target 'JWAnimatedImage_Tests', :exclusive => true do
  pod 'JWAnimatedImage', :path => '../'

  
end
